### ISSUE TITLE
Fork relocatable-python for native packaging

### ISSUE THREAD

**Issue by AkechiShiro** [metacall/distributable-macos#5]
@viferga to package natively for macOS, we need to fork and maintain our own relocatable Python, this repo : https://github.com/gregneagle/relocatable-python

Also merging these two PRs : 
- https://github.com/gregneagle/relocatable-python/pull/26
- https://github.com/gregneagle/relocatable-python/pull/19

**Comment by brillard1** [comment]
On utilzing the relocatable-python for native packaging, it successfully creates the python framework object for the target version till 3.9.9 [[Listed here]](https://www.python.org/ftp/python/3.9.9/)

To check if the framework is universal or not, run the universal script in  terminal
```shell
./python_universal_tester.sh 3.x.x [enter python version]
```

It produces the following output:
```shell
Using Python 3.9.9
      90 libraries (*.so and *.dylib) found in the framework; only        0 are universal!
.
.
.
Python.framework/Versions/3.9.9/Resources/Python.app/Contents/MacOS/Python is not universal!
Python.framework/Versions/Current/Python is not universal!
Python.framework/Versions/Current/bin/python3.9.9 is not universal!
```
The above issues arise due since the current Python framework is not built as a universal binary, which means it only supports a single architecture. This poses a problem as our users may be using different architectures, and we want our framework to be compatible with all of them. The following issues have been identified:

- Lack of support for building universal Python frameworks
- Failure to compile libraries for both arm64 and x86_64 architectures
- Libraries compiled for a specific architecture may cause issues when used on another architecture

To address these issues and build a universal Python framework, the following can be potential solution:

- Use the `./configure --enable-universalsdk` flag when building Python to ensure it is built as a universal binary.
- Use the `lipo` tool to merge the architecture-specific libraries into a single universal library. This can be done by adding a script to our build process that calls lipo after each library is built. [[here]](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary#Determine-Whether-Your-Binary-Is-Universal)
- Ensure that any third-party libraries used by our framework are also built as universal binaries or, alternatively, provide separate builds for each architecture.

By following these steps, we can create a universal Python framework that is compatible with multiple architectures and can be used by a wider range of users.

**Comment by viferga** [comment]
This has been partially solved towards a more general solution, I am going to close this issue for now: https://github.com/metacall/brew-pkg/issues/4
